require:
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
